# Generated by Django 3.2.13 on 2023-04-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230414_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='description',
        ),
    ]
